version: "2.23.3"

services:
  stock-system:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
